# -*- mode: ruby -*-
# vi: set ft=ruby :

$one = <<SCRIPT
apt install -y cmake libpcre2-dev libssl-dev libssh-dev libcurl4-openssl-dev libpcre2-dev libssl-dev libssh-dev libcurl4-openssl-dev 
mkdir 1
cd 1
git clone https://github.com/CESNET/libyang.git
cd libyang/
mkdir build && cd build && cmake .. && make -j$(nproc) && make install
cd ~/1
git clone https://github.com/CESNET/libnetconf2.git
cd libnetconf2
mkdir build && cd build && cmake .. && make -j$(nproc) && make install
cd ~/1
git clone https://github.com/sysrepo/sysrepo.git
cd sysrepo/
mkdir build && cd build && cmake .. && make -j$(nproc) && make install
apt-get install -y pkg-config
echo "/usr/local/lib" | tee /etc/ld.so.conf.d/local-libs.conf
ldconfig
sysrepoctl -l
apt-get install -y libpam0g-dev
cd ~/1
git clone https://github.com/CESNET/netopeer2.git
cd netopeer2/
mkdir build && cd build
cmake -DENABLE_PAM=ON \
      -DLN2_YANG_MODULE_DIR=/usr/local/share/yang/modules/libnetconf2 \
      ..
make -j$(nproc)
make install
ldconfig

SCRIPT

$init = <<SCRIPT
apt update -y
apt upgrade -y
apt install -y python3-pip python3-flask 
apt install -y virtualenv
apt install -y apache2 libapache2-mod-wsgi-py3
SCRIPT

$libyang = <<SCRIPT
apt-get install -y libyang-experimental python3-yang-experimental
SCRIPT

$libnetconf2 = <<SCRIPT
apt-get install -y libnetconf2-experimental python3-netconf2-experimental
SCRIPT

$setup = <<SCRIPT
wget https://github.com/CESNET/Netopeer2GUI/releases/download/v0.2/ncgui.tgz
tar -xzf ncgui.tgz
cp /home/vagrant/shared/ncgui.conf /etc/apache2/sites-available/
a2enmod rewrite
a2enmod proxy_http
a2dissite 000-default.conf
a2ensite ncgui.conf
ln -s /home/vagrant/ncgui /var/www/html/ncgui
mkdir /var/www/html/ncgui/data
cd /var/www/html/ncgui/backend
/home/vagrant/shared/setvenv.sh
cp /home/vagrant/shared/lgui-config.ini /var/www/html/ncgui/backend/config.ini
cp /home/vagrant/shared/netopeer-config.ini /var/www/html/ncgui/backend/liberouterapi/modules/netopeer/config.ini
cp /home/vagrant/shared/run.sh /var/www/html/ncgui/backend/run.sh
cp /home/vagrant/shared/ncgui.service /etc/systemd/system/ncgui.service
systemctl enable ncgui.service
service ncgui start
service apache2 restart
SCRIPT

# uncomment the following line for vagrant < 2.0.0
# Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.vm.define "Netopeer2GUI" do |gui|
    gui.vm.synced_folder ".", "/home/vagrant/shared", create: true
    gui.vm.box = "ubuntu/jammy64"
    gui.vm.network "forwarded_port", host: "8080", guest: "80", auto_correct: true
    gui.vm.network "forwarded_port", host: "8443", guest: "443", auto_correct: true
    gui.ssh.shell = "sh"

    gui.vm.provision :shell, inline: $one
#    gui.vm.provision :shell, inline: $init
#    gui.vm.provision :shell, inline: $libyang
#    gui.vm.provision :shell, inline: $libnetconf2
#    gui.vm.provision :shell, inline: $setup
  end
end
